### PR TITLE
ADD Basic support of Synology Chat Webhooks for Notification

### PR DESCRIPTION
**Pull request by axelbd**
Hello,

I've added Synology Chat as a notification agent. Support is now minimal but if i've time i'll try to add PrettyMetadata.

Regards,

### CODE REVIEW

**Comment by JonnyWong16** [comment]
Why is this necessary? Just use the standard Webhook notifier.

**Comment by axelbd** [comment]
I didn't managed to make it work with the standard Webhook notifier as Chat require the "payload" parameter in the url and the content-type application/x-www-form-urlencoded instead of application/json.

Admitting that somebody managed to do it with the standard Webhook notifier, using a separate notifier simplify the formatting of the notification text by removing the need to write the notification messages in JSON format in the Data tab of the notifier settings.

Do you think this request could be usefull ? If you have a working example of Chat integration with the standard notifier i would gladly use it as i don't really know how many users of tautulli need this specefic notifier.

**Comment by JonnyWong16** [comment]
Then the better pull request is to add the option of changing the `Content-Type` header for the Webhook notifier.

**Comment by axelbd** [comment]
I'll try and test but i doubt this will suffice as the `payload` parameter is another thing that might need to be implemented. Thanks for the help :)

**Comment by Arcanemagus** [comment]
> as Chat require the "payload" parameter in the url and the content-type application/x-www-form-urlencoded instead of application/json.

Note that this _isn't_ a webhook, you should contact Synology to either implement proper webhooks or stop calling them that.

**Pull request closed without merging**
