### PR TITLE
Move vendor libs to standard requirements.txt

### PR DESCRIPTION
**Pull request by fliiiix**
This addresses this issue: https://github.com/Tautulli/Tautulli-Issues/issues/200

Which then will allow to upgrade the codebase to python3. 

Help is appreciated to move everything.

### CODE REVIEW

**Comment by mercury00** [comment]
Ah - I have a list of all the vendor libs. Note that there are three libraries that are not available from requirements.py as they're not in pypi. I'll update a branch with the edits.

**Comment by mercury00** [comment]
Ok, I've finished this with request #1365.

I think. Someone will need to check.

**Comment by fliiiix** [comment]
@JonnyWong16 care to clarify why?

**Comment by JonnyWong16** [comment]
Superceded by #1365.

**Pull request closed without merging**
