### PR TITLE
Add in the IFTTT notifier on the correct channel

### PR DESCRIPTION
**Pull request by rossdargan**
Note I do get an error in this build on the user tab. The error is "DataTables warning: table id=users_list_table - Requested unknown parameter '8' for row 0. For more information about this error, please see http://datatables.net/tn/4"

Don't know if a previous change on this branch causes it, or if it's known already?

Also I stuck with the method I used for sending http posts. It works, and I couldn't easily get the request method to work.

### CODE REVIEW

**Comment by JonnyWong16** [comment]
The dev branch updated the platform/player columns in the datatables. Clearing your cache and refreshing should fix it.

**Comment by rossdargan** [comment]
Thanks JonnyWong16 - I didn't know that.

**Comment by drzoidberg33** [comment]
I'm still planning to get to this.

**Comment by drzoidberg33** [comment]
I had to manually add this code in as merging was too much of a headache. Added a test feature while I was at it.

**Comment by rossdargan** [comment]
Sorry :( I'll take a look and see what you had to change.

Thanks for adding it though!

**Pull request closed without merging**
