### PR TITLE
added iOS WebAPP Icons/Splashscreens

### PR DESCRIPTION
**Pull request by zobe123**
added 1line to plexpy.css - prevents the text is larger than the box (especially TV Shows)
added iOS Icons/Splashscreens exactly how iOS Human Interface Guidelines tells.

### CODE REVIEW

**Comment by JonnyWong16** [comment]
Don't merge Master back into Dev. It causes all those unnecessary commits.

**Comment by zobe123** [comment]
I'm sorry, did not realize that I made this...

**Comment by JonnyWong16** [comment]
Do you think you can add android support as well? 
https://developer.chrome.com/multidevice/android/installtohomescreen

**Comment by zobe123** [comment]
i think so... i didn't tried this yet.
anything else? Windows mobile, Blackberry, Firefox os, Amazon Fire OS?

**Comment by JonnyWong16** [comment]
People actually use those? Lol

I think iOS and Android support is enough for now and covers the majority.

**Comment by zobe123** [comment]
I've added the Icons and added the necessary lines to base.html.
what is the best way to test this now? I 'm just not sure...

**Comment by JonnyWong16** [comment]
Can you rebase and squash into one commit? I only have Android devices to test with, no iPhones or iPads.

**Comment by zobe123** [comment]
first of all, i can do the Tests with Apple devices, no Problem.

but i can't rebase: (I run out of patience...)
image

**Comment by JonnyWong16** [comment]
Moved to #436 .

**Pull request closed without merging**
