### PR TITLE
Add IP address to current activity

### PR DESCRIPTION
**Pull request by JonnyWong16**

### CODE REVIEW

**Comment by drzoidberg33** [comment]
We can make `ip_address` a notification substitution too now.

**Comment by JonnyWong16** [comment]
It will still show up as "N/A" for `state=playing` for anyone not on 0.9.14 though.

**Comment by drzoidberg33** [comment]
That's fine, they will eventually be on 0.9.14 anyway. Or what you can do is make it available but don't document it in the info modal until 0.9.14 is public.

**Comment by Arcanemagus** [comment]
Ooo, am I reading this right and they _finally_ put the IP address in the session info in 0.9.14?

**Comment by drzoidberg33** [comment]
Looks good :shipit:

**Pull request merged**
