### PR TITLE
Initial implementation of server statistics

### PR DESCRIPTION
**Pull request by JonnyWong16**

### CODE REVIEW

**Comment by drzoidberg33** [comment]
Thanks, looks good. Was thinking maybe the new section should be named "Library Stats". Server stats sounds like it has to do with server resources. Thoughts?

**Comment by JonnyWong16** [comment]
Good point. "Library Statistics" makes more sense.

**Comment by drzoidberg33** [comment]
@JonnyWong16 

I think you should also consider limiting the amount of sections pulled (or let the user set a limit) as some people have ridiculous amounts of different sections. Maybe also allow disabling it completely - for me I don't really find much value in knowing how many items are in my library so would be nice to just disable it.

**Comment by JonnyWong16** [comment]
I'll look into it. There's still a lot that can be done with these statistics.

**Pull request merged**
