### PR TITLE
Feature/telegram channel support

### PR DESCRIPTION
**Pull request by onedr0p**
Telegram has added support for sending to channels, I have updated this so chat_id is a string, and will work with the @channelusername chat_id

Here is the documentation:
https://core.telegram.org/bots/api

Thanks!

### CODE REVIEW

**Comment by onedr0p** [comment]
This should be a simple merge :D

**Comment by JonnyWong16** [comment]
~~I'm testing this, but I can't get channels to work.~~

~~I created a new channel (@PlexPytestchannel), and added my bot to the channel as an administrator. Then I set the chat_id to @PlexPytestchannel in the PlexPy settings, but the notification doesn't get sent (Bad request).~~

Needs to be a public channel.

Works, thanks.

**Comment by JonnyWong16** [comment]
Whoops, submit future pull requests to the dev channel please.

I added Telegram channel support in bac5018.

**Comment by onedr0p** [comment]
No problem, glad you got it sorted.

**Pull request merged**
