### PR TITLE
Info pages

### PR DESCRIPTION
**Pull request by JonnyWong16**
Sorry, these are going to be a merge conflict nightmare.

### CODE REVIEW

**Comment by drzoidberg33** [comment]
I have no clue what's going on with all these conflicts. I'm going to merge what I think is right and you can fix it afterwards.

**Comment by JonnyWong16** [comment]
I knew this was going to be a nightmare. I'll fix it up once you merge.

**Comment by drzoidberg33** [comment]
Merged. Love the new info pages btw.

**Comment by JonnyWong16** [comment]
Thanks.
I think you got all the conflicts. I'm not noticing any bugs.

**Pull request merged**
