### PR TITLE
Create self-signed HTTPS certificates

### PR DESCRIPTION
**Pull request by JonnyWong16**
@drzoidberg33 @Hellowlol 

Want to double check this?

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Total cert noob here: Would it be possible to get _real_ certs through https://letsencrypt.org/?

**Comment by Hellowlol** [comment]
Ill test it later today.

**Comment by Hellowlol** [comment]
@Arcanemagus Yes it would, but i think that is something they have to setup them selfes since they are only valid in 60 days (renewal is trivial and a script can run with cron). This pr is about getting a simple self signed cert. If a use wants to use a real one its easy to add in the settings.

**Comment by Hellowlol** [comment]
Worked fine! Nice work.

**Pull request merged**
