### PR TITLE
Run startup tasks after daemonizing

### PR DESCRIPTION
**Pull request by JonnyWong16**
Any negative effects from moving this?

Possibly solves #483

### CODE REVIEW

**Comment by Hellowlol** [comment]
I would move this https://github.com/Hellowlol/plexpy/blob/master/PlexPy.py#L160 above the entire initialize.

**Comment by Hellowlol** [comment]
Let just hope it works :P

**Comment by JonnyWong16** [comment]
How much more can I break it? amirite?

**Comment by JonnyWong16** [comment]
Nope, now the logger is started after the daemon...

**Comment by Hellowlol** [comment]
Just slap it in a print statements. Its just one line and it s warming. I never checked if it would work...

**Comment by JonnyWong16** [comment]
Never mind, init logger on line 95.

Merging, hopefully it doesn't break anything.

**Pull request merged**
