### PR TITLE
IP Address option for notifications

### PR DESCRIPTION
**Pull request by BrianInAz**
I like to be able to see the IP my friends are coming from when I get notifications on their activity. I tested this and it seems to be working fine. I do not know why the last line is showing up in a diff. I did not make any changes to it. I tried my changes first with nano and then with vim but still git is showing an issue with the newline. Curious if you know why that is or how I could fix it in future commits.

Thanks,
Brian

### CODE REVIEW

**Comment by JonnyWong16** [comment]
I already attempted this in #125.

**Comment by BrianInAz** [comment]
OK - thanks. I guess I'll keep it for myself in my fork then. 

Any idea why the newline issue came about?

**Comment by drzoidberg33** [comment]
I've opened this discussion with the Plex devs on maybe adding this into the session XML, which would solve the delay issue.

**Comment by drzoidberg33** [comment]
Closing this as it's something I'll implement once Plex has this available in the web api.

**Pull request closed without merging**
