### PR TITLE
Only schedule job for recently added or monitor remote access if sett…

### PR DESCRIPTION
**Pull request by JonnyWong16**
…ing enabled
#318, #319

bb5aa2b significantly reduces the number of `/metadata` calls.

### CODE REVIEW

**Comment by drzoidberg33** [comment]
Excellent. Going to test this out.

**Comment by drzoidberg33** [comment]
Cool this helps a lot. Integrating.

**Comment by drzoidberg33** [comment]
Seems I was a bit hasty to merge this.

Recently added no longer works at all. I took a look at what's happening and there are two main issues I picked up:
1. There is no time for the `RECENTLY_ADDED_DELAY` to do it's thing. The list of recently added items is cleared out if the previous list was the same so all that code is skipped.
2. When the last item we added is in the same show/season as the new one we're adding it will ignore it because recently added works off the season rating key. Rather use `lastUpdated` to check if there were changes.

**Comment by mbnn** [comment]
So does this now mean we can just Enable Recently Added Notifications but leave the others disabled to simply only push out recently added notifications? Or do the other options also need to stay enabled (Enable Movie Notifications/Enable TV Show notifications etc?).

**Comment by JonnyWong16** [comment]
Currently, you need both checked. I plan on changing this to notify by library section instead of by media type in the future.

**Pull request merged**
