### PR TITLE
Redirect to "home" after shutdown/restart

### PR DESCRIPTION
**Pull request by vertigo235**
In v2, "index" does not load anything

### CODE REVIEW

**Comment by JonnyWong16** [comment]
No, index is correct.

**Comment by vertigo235** [comment]
Interesting, I'm using a docker image so maybe that has something to do with it.

**Comment by Hellowlol** [comment]
index is cherrypy special handler that defaults to the default page.

**Comment by vertigo235** [comment]
Interesting, for v1, calling up /index, redirects to /home, but for me this doesn't happen with v2

**Comment by vertigo235** [comment]
So I guess maybe the issue is somewhere else, I know this is a minor issue.

**Comment by vertigo235** [comment]
I guess it's somewhere in here, I'll play with it later
https://github.com/JonnyWong16/plexpy/blob/v2/plexpy/webserve.py

**Pull request closed without merging**
