### PR TITLE
Adds execute permission to fedora.centos and systemd init-scripts

### PR DESCRIPTION
**Pull request by wilmardo**
These two init-scripts were missing the execute permission, fixed it with this PR.
If someone creates a symlinks from /etc/init.d/plexpy to the file in the git directory it won't work without the execute permission.
The other init-scripts in the directory had the execute permission already set correctly.

Sorry for the PR on master :)

### CODE REVIEW

**Comment by wilmardo** [comment]
Any update on this?

**Comment by JonnyWong16** [comment]
Please switch this to the `nightly` branch.

**Comment by wilmardo** [comment]
Done but the changes seems to be done already, closing this :+1:

**Comment by wilmardo** [comment]
Woops, spoke to soon. Diff view doesn't list these changes apparently, just checked the nightly branch locally and these changes aren't yet applied. Reopening, sorry!

**Comment by JonnyWong16** [comment]
Thanks.

**Pull request merged**
