### PR TITLE
Adds notification parameter that returns volume label (drive letter o…

### PR DESCRIPTION
**Pull request by dmumm**
…r UNC sharepoints) for windows servers

## Description

Adds a parameter to notification agents that returns string of volume where filepath is located 

### Screenshot

image

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods

### CODE REVIEW

**Comment by JonnyWong16** [comment]
I don't see any point in this. Just use the `file` parameter.

**Comment by dmumm** [comment]
> I don't see any point in this. Just use the `file` parameter.

Personally I added it for myself as my server has had issues with too many streams per drive ruining performance and this notification was to help users know what drives were currently being used to diagnose if random read disk speed was a reason for buffering. As the current python functions in the notifications do not include truncating a string the `file` param wasn't really an option (unless I'm missing something)

**Comment by JonnyWong16** [comment]
That just sounds like a very niche use case.

I'm fairly certain this works (with `notify_text_eval = 1` enabled):
```
{`file[:2]`}  -->  M:
```

Sorry, I won't be merging this PR.

**Comment by dmumm** [comment]
> I'm fairly certain this works (with `notify_text_eval = 1` enabled):
> 
> ```
> {`file[:2]`}  -->  M:
> ```

That's my bad, that does work but I swear I tested this before (likely messed something up) and assumed the functionality wasn't there as it wasn't listed and was my read of what Issue #1649 was requesting.

**Pull request closed without merging**
