### PR TITLE
Add the repository link right of PlexPy brand on nav-bar.

### PR DESCRIPTION
**Pull request by onedr0p**
A small change to add a link to the github repo. It's pretty minimal and could go anywhere if not on the left side like I have it.

### CODE REVIEW

**Comment by JonnyWong16** [comment]
I don't think this should be on the nav-bar. Instead somewhere on the Settings > General page.

**Comment by onedr0p** [comment]
Alright, I'll take a look and see where I can place it.

**Comment by JonnyWong16** [comment]
Maybe a [Gitter](https://gitter.im/drzoidberg33/plexpy) link as well. But there is not font awesome icon for Gitter.

**Comment by JonnyWong16** [comment]
Repository and Gitter link added to settings page in v1.3.7. No pretty font-awesome icon though.

**Comment by onedr0p** [comment]
Awesome, apologies for my laziness, to many things going on at once :)

**Pull request closed without merging**
