### PR TITLE
Quick fix for high contrast mode

### PR DESCRIPTION
**Pull request by JonnyWong16**
Not sure if this is the best way to fix this, but it works for now

### CODE REVIEW

**Comment by drzoidberg33** [comment]
I really don't think this is a maintainable way to go forward.

Either we must go back to using src tags for all images and a Python function to fix aspect ratio issues or use a single javascript function to do this. Having the HC checks all of the place is not a proper solution.

**Comment by JonnyWong16** [comment]
I agree. This might not even be worth getting to work for the couple of people using high contrast mode.

Alternatively, the script can be put into a GreaseMonkey/TamperMonkey script that will do the image replacements in the user's browser.

**Comment by drzoidberg33** [comment]
I like the idea of having the user fix this on their end with a script like you suggested. There are probably like 0.00001% of people using PlexPy with high contrast mode.

**Comment by JonnyWong16** [comment]
Custom userscript available here:
https://github.com/JonnyWong16/plexpy-highcontrastmodefix

**Pull request closed without merging**
