### PR TITLE
More stylized homepage statistics and other style changes

### PR DESCRIPTION
**Pull request by JonnyWong16**
- Fixed some formatting on user page and posters on info page
- Fixed tab spacing in css file
- Fallback to show poster if season poster is unavailable
- Dynamically adjust user recently watched items
- Style changes
- Added missing metadata
- Don't show metadata field if data is unavailable

### CODE REVIEW

**Comment by drzoidberg33** [comment]
Thanks for the styling fixes and improvements.

The home stats posters are broken now though, they're overflowing their containers.

**Comment by JonnyWong16** [comment]
I made it look like that.
Home Posters

**Comment by drzoidberg33** [comment]
Ah. It looks broken mainly because they're not the same size as the user and platform cards.

**Comment by JonnyWong16** [comment]
I can't think of a way to change the user and platform cards since they don't have a poster. I'm open to ideas if you have some.

**Comment by drzoidberg33** [comment]
I'd just make sure the cards stay the same size and the content should stay in the bounds of the cards.

Probably just best to leave the posters the same size as they originally were.

**Comment by JonnyWong16** [comment]
Home page statistic cards have been reverted.

**Comment by drzoidberg33** [comment]
Thanks, love the changes. You fixed a lot of stuff that annoyed me about the old styles that I never got round to fixing.

**Pull request merged**
