### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by zobe123**
Add tvOS and edit platform image name.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
You'll need to rebase your commit on the latest `dev`, you have a bunch of extraneous commits in this PR.

**Comment by zobe123** [comment]
Thank you for the hint. I'm totally new in this. Can you explain? Thx

**Comment by Arcanemagus** [comment]
It looks like when you started making this patch your version of the `dev` branch was out of date, so this branch was based off an older version of the dev ranch (or even the `master` branch?).

The following should ensure your branches are up to date, and then set the "base point" for this `patch-1` branch to the current state:

``` ShellSession
git fetch --all -p
git rebase dev
```

You should run that from a terminal that has this branch currently checked out.

---

For your information here is how you would keep your copy of the branches up to date without getting those extra "Merge commits" you get from doing it in the GitHub web interface.

``` ShellSession
git fetch --all -p
git checkout master; git merge remotes/drzoidberg33/master; git push
git checkout dev; git merge remotes/drzoidberg33/dev; git push
```

**Comment by zobe123** [comment]
thx a lot, but it seems this is a permission Problem:
i get this:
   <pre>Username for 'https://github.com': zobe123 
Password for 'https://zobe123@github.com': 
remote: Permission to drzoidberg33/plexpy.git denied to zobe123.
fatal: unable to access 'https://github.com/drzoidberg33/plexpy.git/': The requested URL returned error: 403</pre>

**Comment by Hellowlol** [comment]
Simple solution, browse the file you want to change on drzoidberg33 github page, press edit, do your changes, click save, send a pr.

**Comment by zobe123** [comment]
@Hellowlol - that was exact i did. then i got: <pre>You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork zobe123/plexpy, so you can send a pull request. </pre>

pull request button shows me: 
drzoidberg33/plexpy Patch 1 #309 opened 9 hours ago by zobe123

**Comment by JonnyWong16** [comment]
I implemented your change in c65d989.

Closing this PR.

**Comment by zobe123** [comment]
@JonnyWong16 is it OK how i submitted my ideas/changes? or is there a better way?

**Comment by JonnyWong16** [comment]
Your changes was fine. Just make sure you're working of the latest dev branch instead of master.

**Pull request closed without merging**
