### PR TITLE
Multi-Server Support

### PR DESCRIPTION
**Pull request by zSeriesGuy**
This update primarily adds support for multiple Plex Servers. As part of this, servers are automatically discovered from the plex.tv account and populated into the database.

Changes:
* Monitoring:
  * New: Support for monitoring multiple Plex Servers.
  * New: Support for monitoring rclone mount.
  * Change: Changed Get for Plex Updates to 15 minute interval.
* UI:
  * New: Dashboard Server Status card.
  * New: Added server name to lists (Libraries, History, User History) 
* History:
  * New: Import for Tautulli databases
  * New: Filter by server
* Graphs:
  * New: Added server selection
  * New: View by media type or server
* Newsletters:
  * New: Added Server selection
* Notifications:
  * New: Added rclone up/down notification
* Users:
  * New: Added Guest access levels
    * No Access
    * Guest - Can see only their own history on the servers they are friended to. This is the same functionality as in previous releases.
    * PowerGuest - Can see all users' history and all library sections but only on the servers they are friended to.
    * SuperGuest - Can see all users' history and all library sections on all servers. But no access to settings.
    * Admin - Full access to all controls.

The rclone mount monitoring is enabled in Settings->Plex Media Servers then activated on each individual server in the server configuration.

I also removed the unicode designation on the logger messages in preparation for PY3. I can put those back if you prefer.

I apologize for not using small commits. First time doing something like this.

### CODE REVIEW

**Comment by rjsears** [comment]
Awesome. However, how do we upgrade? My instance is showing that I am "All up to date" with version 2.1.26.

Thanks for the awesome work!

**Comment by Arcanemagus** [comment]
> My instance is showing that I am "All up to date" with version 2.1.26.

That's because this isn't a release of Tautulli, it's a PR to the Tautulli repo.

**Comment by rjsears** [comment]
Well, totally missed that @Arcanemagus - thank you!

**Comment by zSeriesGuy** [comment]
@JonnyWong16 Are you not interested in these changes?

**Comment by JonnyWong16** [comment]
Good job for doing this, but this is literally impossible to review (8845 additions, 5234 deletions). This will not get merged in its current state. I can't merge something in confidence just "because it seems to work fine". I don't know if it breaks anything else. I don't know what other feature you may have changed. I will leave this pull request open.

**Comment by zSeriesGuy** [comment]
Could this be implemented if I redo the changes in smaller submissions? I, as well as a lot of other folks, sure would like to have multi-server support.

**Comment by Soitora** [comment]
Multi Server support should be prioritized, this is great.

**Comment by vistalba** [comment]
@JonnyWong16 @zSeriesGuy Please find a way to make this possible together. It will be a awesome feature and I don't need to run multiple tautulli dockers :)

**Comment by jesselsullivan** [comment]
@JonnyWong16 Can we make this branch public since a lot of people want it? I trust @zSeriesGuy it's not too broken lol

**Comment by jesselsullivan** [comment]
PS, been looking for a good side project to get my python skills refreshed so idk, if I get some free time on the weekends I'll see what I can contribute :)

**Comment by Arcanemagus** [comment]
The only thing stopping you from using that fork is that we provide no support for it. Please remember that in the current form this is **not** getting merged.

Note also that as this makes several incompatible changes to the database you **can't** switch back to Tautulli after using that.

**Comment by jesselsullivan** [comment]
Oh ok, I see how now, I'm actually a bitbucket guy more than github ha

**Comment by zSeriesGuy** [comment]
I backed off the unicode indicator changes to the logger messages. This reduced the number of changes from 91 files to 82 files, of which only 24 are py code. But there are still a lot of total changes.
This implementation, to make it functional, required a lot of changes. 

I guess to satisfy your requirements, I would have to completely redo these changes is very small non-functional changes until ready to activate. Guidance would be appreciated.
However, I doubt I will do that since this project did cost be a lot of time already.

This is a shame since so many folks seem to really desire this functionality and you have a really nice product.

I hope you will eventually come thru with support for multiple servers for your many followers.

**Comment by jesselsullivan** [comment]
I'll pull your changes later, and I haven't had time to mess around with it much either, but I've been treating this like UAT and it's worked fine for me so far :) I'll make an issue on your fork if I find anything wrong

**Comment by samwiseg0** [comment]
Again, there is nothing stopping anyone from using this fork. As for merging these changes. In order for the product to remain well supported and reliable we would have to audit every change. We would also have to go through every piece of functionality that was touched and verify it is working as intended. In its current form this is nearly impossible.

**Comment by zSeriesGuy** [comment]
@samwiseg0 When I wrote this code, I had hoped to contribute to this fine product and provide a function that a lot of folks were asking for. I had hoped it would be merged. Sure, folks can use my fork. But they won't since it will diverge from base unless I duplicate your changes. This is not what I intended.

Is there no other solution to testing? Even if it took some time?

**Comment by Soitora** [comment]
Do you have a picture of how it looks with multiple servers?
What if I use your code and then you stop supporting it, how does it merge back into normal Tautulli?
And, do you keep it up to date with Tautulli updates?

**Comment by samwiseg0** [comment]
This conversation should be for this PR only. If you have specific questions about the fork please contact the developer on their fork. 

You will not be able to go back to Tautulli if you use this fork. This has already been stated. https://github.com/Tautulli/Tautulli/pull/1340#issuecomment-478208660

**Comment by ghost** [comment]
@zSeriesGuy I'll donate you 200€ via PayPal if you manage to get this commit merged. This is a must-have feature for me!

**Comment by zSeriesGuy** [comment]
@whalehub Merging is not up to me. The owner indicates that my PR is too large to adequately test and verify.
In the meantime, you are welcome to run my fork. But note the comments above about support.
So I would suggest you stand up a new Tautulli instance.
You can copy in your config.ini and tautulli.db to the new instance from each of your current servers (one at a time) and let the code migrate it. Then you can import them to merge the current separate instances into a single database.

Perhaps if enough people test my fork and provide feedback here, it might be helpful to the owner.
Or perhaps if you offered to 200€ to @JonnyWong16, the owner of this repository...

**Comment by ghost** [comment]
@zSeriesGuy My apologies! Do you have a dockerized version of your fork?

@JonnyWong16 Would 200€ change your mind about merging this PR? :-P

**Comment by JonnyWong16** [comment]
As I already stated above, I will not merge this without doing thorough testing and checking over every line of code that was changed. I personally don't have the time to spend on doing that in the near future. I do have other things to do in my life; Tautulli is a hobby.

I do acknowledge that this is a feature that many people want, but it is a very complicated feature to implement (probably the most complicated ever for this project). It must be done properly because it is essentially rewriting the core of Tautulli. I have personal standards and I will not push out a half-assed attempt at a feature. For reference, I was working on newsletters in Tautulli for over a year before I felt that the quality was up to my standards for this project and could be released.

With that said, I'm **_not_** saying that the work @zSeriesGuy has done here is not done properly. or poor quality. The fact is that I have not reviewed it yet.

**Comment by whalehub** [comment]
@zSeriesGuy Would it be difficult to add support for monitoring multiple Plex servers that are linked to different Plex accounts in Tautulli?

**Pull request closed without merging**
