### PR TITLE
Capitalise "Python"

### PR DESCRIPTION
**Pull request by dmptrluke**
This is a super minor and pointless thing, but it seem that in official documentation Python is capitalised, so thought I'd suggest using it here.

### CODE REVIEW

**Comment by drzoidberg33** [comment]
All PRs should be made to the dev branch.

**Comment by Hellowlol** [comment]
Alot of prs are getting closed since they are not to dev. I think it would nice if it also stated that all prs should be sendt to dev. (I know its mentioned in the branches paragraph, but i didnt read that, and suspect other are doing the same)

**Comment by drzoidberg33** [comment]
The info is in the correct place, I believe it also comes up when making the PR to make sure you've read the contributions document.

screenshot 2015-10-15 10 53 56

**Comment by Hellowlol** [comment]
Yes, but that doesnt help as long as the info is in the branches header. That info should be moved to the https://github.com/drzoidberg33/plexpy/blob/master/CONTRIBUTING.md#pull-requests.

Under branches, it should state that master is "stable" and that the brave and bold can run dev to get the latest and the greatest.

Anyway, its up too you. Just thought it was worth mentioning since this happens on a weekly basis (from the time i started to watch your repo)

**Pull request closed without merging**
