### PR TITLE
add summary_short params

### PR DESCRIPTION
**Pull request by Akior**
Want to use summary params for notification agent
Get telergam limitation (1024 symbols) for caption message because summary is oversize
Create short summary block

This method cut text and can cut word for N symbols. 
Maybe there are another method of deal with it, but Im not high skill with python.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
You need to change this to target the `nightly` branch, as explained in [CONTRIBUTING](https://github.com/Tautulli/Tautulli/blob/master/CONTRIBUTING.md).

**Comment by JonnyWong16** [comment]
I would much rather limit the text to 1024 characters for the Telegram agent specifically, instead of some arbitrary 400 characters.

See 688d28b5ea2360769bd58504fc8fb905521ce676 on how Discord is limited to 2048 characters.

**Comment by Akior** [comment]
> I would much rather limit the text to 1024 characters for the Telegram agent specifically, instead of some arbitrary 400 characters.
> 
> See [688d28b](https://github.com/Tautulli/Tautulli/commit/688d28b5ea2360769bd58504fc8fb905521ce676) on how Discord is limited to 2048 characters.

The limit of telegram is 1024 characters, but sending message for English letters is 

     sendPhoto -caption "EnglishText" 
and for Russian example:

     sendPhoto -caption "\u0420\u0443\u0441\u0441\u043a\u0438\u0439\u0442\u0435\u0441\u0442"
Tau have code:

     if len(text) > 1024:
                    data['disable_notification'] = True
So for the same limit char we have not same length of text.
If I do something like this:

     if len(text) > 2048:
                    data['disable_notification'] = True
     else:
                    data['caption'] = text[:1745] + (text[1745:] and '...')
English text will be drop if char more than 1024, but Russian will work. English text error:

     Request response: {"ok":false,"error_code":400,"description":"Bad Request: MEDIA_CAPTION_TOO_LONG"}

Anyway, the biggest text is "summary", so limit to summary_short will work for all Languages

**Comment by JonnyWong16** [comment]
The issue isn't with `/sendPhoto`. The caption is already limited to 1024 characters. You don't need to change that.

The issue is the 4096 character limit for the `/sendMessage`.

https://github.com/Tautulli/Tautulli/blob/master/plexpy/notifiers.py#L3453

```
data['text'] = text[:4093] + (text[4093:] and '...')
```

**Comment by Akior** [comment]
> The issue isn't with `/sendPhoto`. The caption is already limited to 1024 characters. You don't need to change that.
> 
> The issue is the 4096 character limit for the `/sendMessage`.
> 
> https://github.com/Tautulli/Tautulli/blob/master/plexpy/notifiers.py#L3453
> 
> ```
> data['text'] = text[:4093] + (text[4093:] and '...')
> ```

I mean limitation of caption works bad. I can send more RU text with fix > 2048. 
Looks like len(text) != len(limitation) because unicode

If you don't want to add summary_short, you can close request.
But I will be much appreciated, If you can add some fix for sendPhoto with caption for Ru(or maybe any non English lang) segment

**Comment by JonnyWong16** [comment]
Text just needs to be decoded to Unicode.

https://github.com/Tautulli/Tautulli/blob/master/plexpy/notifiers.py#L3442

```
if len(text.decode('utf-8')) > 1024:
```

**Comment by Akior** [comment]
> if len(text.decode('utf-8')) > 1024:

                if len(text.decode('utf-8')) > 1024:
                    data['disable_notification'] = True
                else:
                    data['caption'] = text.decode('utf-8')[:1021] + (text.decode('utf-8')[1021:] and '...')

But we don't need 1024 char check anymore. 

Can you add this to tau main ?

**Comment by Akior** [comment]
Your solution doesn't split text of caption. It split telegram message:
Снимок экрана от 2020-01-21 13-36-13
Without 1024 check and :

     data['caption'] = text.decode('utf-8')[:1021] + (text.decode('utf-8')[1021:] and '...')

Снимок экрана от 2020-01-21 13-38-49

**Comment by JonnyWong16** [comment]
That is correct behavior. Less than 1024 is a caption, more than 1024 is a separate message.

**Comment by Akior** [comment]
> That is correct behavior. Less than 1024 is a caption, more than 1024 is a separate message.

Can you add "force caption" option with 1024 splitting?

**Comment by JonnyWong16** [comment]
No.

**Pull request closed without merging**
