### PR TITLE
allow refresh of images

### PR DESCRIPTION
**Pull request by Hellowlol**
Allow refresh of images and fix bug where a disabled cache still would
use the cache

### CODE REVIEW

**Comment by JonnyWong16** [comment]
That was fast...

**Comment by Hellowlol** [comment]
Well take a look at the diff, wasnt any work really :P. Dunno if it should be a button somewhere or if this something they have to do manually.

**Comment by JonnyWong16** [comment]
There should probably be a button. That's going to be quite a task to add everywhere.

**Comment by Hellowlol** [comment]
Then don't. I wouldn't be arse with that. Just add a button in the view show/movie and/or write a general function that recaches every image of every show/ep/movie

**Comment by JonnyWong16** [comment]
That's probably even more difficult when the files are hashed.

**Comment by Hellowlol** [comment]
Ah true, i just thought we compare the hash but i forgot that we also include the filesize etc. That would be major pain :P

**Pull request merged**
