### PR TITLE
Add Facebook notification agent

### PR DESCRIPTION
**Pull request by JonnyWong16**
Feedback on this? Especially the way I use the redirect URL to get the user access token, I'm sure this is prone to errors.

I didn't want to hardcode a Facebook app ID/secret. Alternatively, we could setup our own redirect server url so we can use our own app ID/secret?

I would also like to remove the hardcoded Twitter key/secret.

### CODE REVIEW

**Comment by keithah** [comment]
Im trying to use this and getting:

Error sending Facebook post: Write operations require an access token

in the logs. Any ideas?

**Comment by JonnyWong16** [comment]
Did you follow all the instructions?

**Comment by keithah** [comment]
Yes.

**Comment by JigSawFr** [comment]
@JonnyWong16 need proxy support. As i use Docker, app bind to localhost and port given, but is accessible only by an other ip/domain and port. So can we force return url for facebook agent ?

**Comment by keithah** [comment]
But I did notice that the 'request authorization' button did not do a popup, instead it just said 'success' in the corner. Maybe thats what is supposed to grant write permission?
I updated to the latest dev build, still same error.

**Comment by JonnyWong16** [comment]
@JigSawFr Yeah, I'll need to change that.

@keithah I just confirmed with someone on the [Gitter](https://gitter.im/drzoidberg33/plexpy) chat that the authorization process works on the latest dev build and `localhost`.

**Comment by JonnyWong16** [comment]
@JigSawFr @keithah I pushed an update to the dev branch. Could you guys test the Facebook authorization again?

**Comment by JigSawFr** [comment]
@JonnyWong16 seems to workas expected. Test passed, i'm waiting for real notifs :)
Thanks you !

**Comment by JigSawFr** [comment]
It's working great !
Is it possible to post custom notifications for Facebook ? Official poster of movie for example with notification <3

**Comment by JonnyWong16** [comment]
It's possible, but I haven't thought of the best way to do that yet.

**Comment by JigSawFr** [comment]
@JonnyWong16 Just tested with adding Emoji (native column http://apps.timwhitlock.info/emoji/tables/unicode), working so great on Facebook and better on mobile. Love it !

Question, any idea on how i can make new line ?

**Comment by JonnyWong16** [comment]
Just add a new line in the textbox where you enter the notification body.

**Comment by JigSawFr** [comment]
So great, a preview :

Facebook Agent

**Comment by JonnyWong16** [comment]
Wow, that's nice. I never thought about using the icons.

**Comment by JigSawFr** [comment]
@JonnyWong16 imagine with poster :heart_eyes: 
In my mind, we need to change post type by image/photo (or let user choose) type with description :)

There is my code to produce this:
In recently added, replace by:

```
🎥 {title} ({year}) a été ajouté !

<movie>🕑 Durée: {duration} min.

💯 Note: {rating}/10

📹 Studio: {studio}

🎯 Genres: {genres}

🎭 Acteurs: {actors}

🎫 Synopsis: {summary}</movie>
```

**Comment by JigSawFr** [comment]
@JonnyWong16 A friend tried to setup this notification provider but he is facing a strange problem:
`(#200) Insufficient permission to post to target on behalf of the viewer`
We have follow all steps as it's described and i followed for mine group/facebook notifier

**Solved** by https://www.facebook.com/settings?tab=applications
Change Application view to Public

**Comment by JigSawFr** [comment]
@JonnyWong16 there is a problem we are facing, tested with 2 groups / apps / and many users.
When we post in group normally with facebook (with our account), members can view my posts. But if it's the application which is posting in group, they don't see messages (but me yes). Maybe an autorization problem ? Thanks

**Solved** by turning app state to "live" in Status & Review (No need to submit app for approval !)

**Comment by JonnyWong16** [comment]
@JigSawFr Thanks for the info.

**Pull request merged**
