### PR TITLE
Quater values for History Watch Status

### PR DESCRIPTION
**Pull request by herby2212**
## Description

Introduces quarter values to the watch status.

The existing calculation in the `datafactory` was extended to account for the new status options. The `history_table` was changed from using FontAwesome icons to a custom css class _(I took your example there as a basis)_.

### Screenshot
**Before**
image

**After**
image

Include screenshots if the changes are UI-related.

### Issues Fixed or Closed

- Implements #2156 

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods

### CODE REVIEW

**Comment by JonnyWong16** [comment]
Can you fill the circle clockwise?

- Quarter: top-right
- Half: top-right and bottom-right
- Three Quarters: top-right, bottom-right, and bottom-left
- Full: full

**Comment by herby2212** [comment]
> Can you fill the circle clockwise?
> 
> * Quarter: top-right
> * Half: top-right and bottom-right
> * Three Quarters: top-right, bottom-right, and bottom-left
> * Full: full

It should already be this way.

**Comment by JonnyWong16** [comment]
image

**Comment by JonnyWong16** [comment]
Oh my bad dark is empty, white is full.

Half circle is still backwards.

**Comment by herby2212** [comment]
> Oh my bad dark is empty, white is full.
> 
> Half circle is still backwards.

Yeah half circle is the wrong way around 😄. I will change it.

**Comment by herby2212** [comment]
> > Oh my bad dark is empty, white is full.
> > Half circle is still backwards.
> 
> Yeah half circle is the wrong way around 😄. I will change it.

Done.

**Comment by JonnyWong16** [comment]
Left is new, right is old. Circle is floating above the baseline. Change the light colour (border and full) to `#eeeeee` and dark colour (partially filled) to `#2b2b2b` to match the old icons.

image

**Comment by herby2212** [comment]
> Left is new, right is old. Circle is floating above the baseline. Change the light colour (border and full) to `#eeeeee` and dark colour (partially filled) to `#2b2b2b` to match the old icons.
> 
> image

Done.

**Review by JonnyWong16 — APPROVED** [review]

**Pull request merged**
