### PR TITLE
MQTT improvements

### LINKED ISSUE #1415: JSON Escaping For Notifications
The MQTT notifier is useful for a machine to quickly receive and process notifications. It even already wraps the "message" subject, body, and topic into JSON. However, it's difficult to parse the message body by machine. Ideally support for just listing the parameters you want, and they get stuffed into the root JSON object would be great, but I suspect that would be difficult since the notification system is generic. Instead, how about a text modifier (similar to the upcase and downcase modifiers) that escapes the parameter for insertion into JSON. I.e.:

```json
{
  "username": "{username}",
  "title": {title!json}
}
```

(notice no quotes around the {title} - it would be expected that they would be added, because it's outputting a valid JSON string)

So I'd still have to build up my body and write the JSON, and on the receiving end I'll have to double-decode the JSON (since the body will be encoded as a string in the entire JSON message, but at least it would be machine processable without resorting to any tricks.

### PR DESCRIPTION
**Pull request by ccutrer**
## Description

This is a series of changes to improve the machine readability of notifications sent via MQTT. In particular, being able to send to multiple topics based on any parameter (i.e. I plan to include the {player_id} in the topic so that if I want to do automations for what's happening in a particular room, I only have to subscribe to that topic), and being able to either send bare 
text not wrapped in JSON for simpler handling at the recipient OR being able to build a full JSON object with proper escaping to bundle a lot of information in a single notification.

Fixes #1415 and #1416.

A couple of notes:
 * I'm more than willing to split each commit into its own PR if you would prefer to review that way.
 * I didn't love the deferred import of build_notify_text, but it was necessary to avoid a circular dependency. Possibly break that method out into a separate module? Also, possibly refactor it so that it doesn't need to do repetitive work on both subject and body, and just call it twice.
 * It might make more sense to just have the subject correspond to the MQTT topic, and the body the payload, but that would be a breaking change (there would no longer be a topic configuration setting at all). This would also eliminate the need for the omit_subject option.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods

### CODE REVIEW

**Comment by JonnyWong16** [comment]
I don't understand the purpose of the `!j` modifier.

Your example:
```
{{ "title": {title!j}, "media_type": {media_type!j} }}
```
Is the exact same as enclosing parameters in quotes:
```
{{ "title": "{title}", "media_type": "{media_type}" }}
```
`json.dumps(str(value))` is the same as just `str(value)` which is just `"{value}"`.

---

Using `build_notify_text` isn't necessary. The topic doesn't need to filtering `<tags>` and all the custom text modifiers. Just format the topic directly. 

```python
topic = self.config['topic'].format(**kwargs['parameters'])
```

---

`omit_subject` should be `incl_subject` to match the other notification agents. Checkboxes should be "check to enable something" and not "check to disable something". It will need to be checked by default so it doesn't break existing configs.

**Comment by ccutrer** [comment]
`json.dumps(str(value))` is _not_ the same as `str(value)`. It does JSON escaping so that it can be machine parseable. Notice the first example, where the param has a double quote embedded. And in the output, that double quote is properly escaped to form a valid JSON string.
```python
>>> json.dumps("stuff \"\\ and more")
'"stuff \\"\\\\ and more"'
```
Double quotes and backslashes are not an issue in a lot of the fields, but they are for user readable/editable metadata like item titles or player names.

As for the topic and subject options, I've been thinking more and I don't love the direction I'm taking here. I'm thinking instead of a `incl_subject` config, have a `use_subject_as_topic` config, thereby ignoring the topic in the notifier config. It means I don't have to bother with any formatting at all, and I also don't have to have a new option that defaults to "on" in order to be backcompat and non-negative.

**Comment by JonnyWong16** [comment]
Yes, it only makes a difference if a value has a double quote. Otherwise `{param!j}` and `"{param}"` are identical. It's not really an intuitive way to just escape a double quote.

I would much rather have a setting to parse the text as json instead similar to webhooks. No json modifier, no omit/include subject, just one checkbox to enable parsing both the subject and body as json.

---

I don't like the idea of `use_subject_as_topic`. I don't want there to be two possible places to enter a topic which will cause confusion.

**Comment by ccutrer** [comment]
I looked at the webhooks stuff, and I have to admit I don't understand how that works to handle escaping issues. And googling it just led to people complaining that the body they entered couldn't be parsed as JSON, and no response as to how it's supposed to be used. It looks like the webhook notifier takes the body (which has already had the parameters formatted in), and parses it as JSON. then it takes the resulting hash and embeds it in some wrapper json (with a key of either json or data, depending on if a header was set). But if {title} has a a double quote or a slash in it, it would be impossible for body to be properly formed JSON _before_ the JSON parsing, thus throwing an error.

> no omit/include subject

So you're saying a single option to say "parse the subject and body as JSON". I'm not sure how that accomplishes any of my goals here. Maybe I should illustrate how I have it set up right now, and it's working beautifully with my home automation system.

Here is the configuration for my first notifier:
https://www.dropbox.com/s/17ycoyax5qzs1f4/Screen%20Shot%202021-04-29%20at%209.49.50%20AM.png?dl=0
and
https://www.dropbox.com/s/0ayuxg0pby7arkp/Screen%20Shot%202021-04-29%20at%209.50.23%20AM.png?dl=0

and a second:
https://www.dropbox.com/s/vtnlgj0zcoyhy6d/Screen%20Shot%202021-04-29%20at%209.50.41%20AM.png?dl=0
and
https://www.dropbox.com/s/6zgy2mhpsf9sa3a/Screen%20Shot%202021-04-29%20at%209.50.54%20AM.png?dl=0

I also have two more that publish parent_rating_key and grandparent_rating_key. Then in MQTT, the resulting topics look like this (ignore the value of the root tautulli topic; that one is leftover from testing):
https://www.dropbox.com/s/393w3kix6tqdncr/Screen%20Shot%202021-04-29%20at%209.51.42%20AM.png?dl=0

I plan on adding more fields later, but this is enough for now for my code to identify exactly what is playing and take appropriate actions (it adjusts the zoom on the projector depending on the content's aspect ratio).

This make it easy for my HA system to link one item to tautulli/ce2988369206e191-com-plexapp-android/item_key and one item to tautulli/ce2988369206e191-com-plexapp-android/last_action and not have to do any post-processing. I use OpenHAB, which it _can_ extract values from JSON encoded topics, but it's a bit of a pain. I know other home automation systems can work better stuffing a lot of information into a single topic, but again, that will only work correctly if the JSON is properly encoded.

**Comment by JonnyWong16** [comment]
(Your screenshots are all out of order)

I didn't say remove formatting in the topic. Keep that, but just format it directly like I mentioned above.

I'm just saying have a checkbox so you can enter json directly into the subject and body. The webhook notification agent already has all the code to properly escape quotes and everything and you don't need the double curly brackets.

Example, in the webhook body:
```
{
    "title": "{title}",
    "media_type": "{media_type}"
}
```
will automatically be formatted to
```
{
    "title": "A title with \"quotes\"",
    "media_type": "movie"
}
```
compared to your solution which has extra brackets and modifiers
```
{{
    "title": {title!j},
    "media_type": {media_type!j}
}}
```

**Comment by ccutrer** [comment]
Oh, okay, I thought you were referring to no other checkboxes. I can definitely simplify the topic formatting.

And I definitely agree if your description of webhook's formatting is how it works, that would be far easier. I just don't understand how that's possible, but I'll play around with it. It's been a year or 15 since I've used python for more than just a tweak or two.

**Comment by ccutrer** [comment]
Gah, silly dropbox. I think I pasted before they were uploaded. Sorry. Post updated with correct links.

**Comment by ccutrer** [comment]
Ohhhh, I get it now. `build_notify_text` special cases the webhooks notifier, parses the template as JSON, then formats each individual K/V pair. it then dumps it back to a JSON string properly. OK, I'll hook in there, if configured, for MQTT messages

**Comment by begunfx** [comment]
Can we please get this re-opened?

**Comment by JonnyWong16** [comment]
If you are offering to implement the required changes, the please make those changes and submit a new PR.

**Comment by begunfx** [comment]
I am not.  I was just submitting the issue in hopes that someone would address it.  Since you directed me here, I thought that this was an effort to address that issue, that's why I asked if it could get re-opened.

**Comment by JonnyWong16** [comment]
OP abandoned this PR over a year ago, so any changes will require someone to submit a new PR.

**Comment by ccutrer** [comment]
I'm still watching ;), but haven't been motivated to address anything because I've been busy with many other projects. I might be more motivated to work on it now knowing that someone else would appreciate it.

**Comment by begunfx** [comment]
Thanks for chiming in @ccutrer.  I would definitely appreciate it if this was fixed/improved!

**Comment by ccutrer** [comment]
@JonnyWong16:

I've pushed an updated branch, if you could reopen please. I think I've addressed all of your comments:

 * use a simple `topic.format(**parameters)` instead of using `build_notify_text`
 * use `incl_subject`, defaulting to on, instead of `omit_subject`
 * added an option to parse MQTT bodies as JSON, triggering the same logic as the webhook agent uses, rather than having a format specifier and having to double up literal braces.

**Comment by begunfx** [comment]
Thanks, @ccutrer!  @JonnyWong16, looking forward to your action on this PR.

**Comment by JonnyWong16** [comment]
Please submit a new PR based on the latest `nightly` branch.

**Comment by ccutrer** [comment]
I did rebase on top of the latest nightly, but I'll be happy to open a new PR.

**Pull request closed without merging**
