### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by lngarrett**
I've created this PR to add Docker support to the project. I also added Circle CI support to commit successful builds to the Docker Hub repository. This would combine to allow someone to install simply by running a one liner such as 

`curl https://raw.githubusercontent.com/lngarrett/plexpy/master/docker_run.sh | sh`.

How does this app handle persistent data? I need to modify the docker run command to create a volume for that.

Also, this repo would need to [support](https://github.com/settings/connections/21951569) Circle CI. I'm currently pushing my fork to the [Hub](https://hub.docker.com/r/lngarrett/plexpy/). I know you currently support Travis CI - Travis CI could be configured to do the push as well.

### CODE REVIEW

**Comment by drzoidberg33** [comment]
I've never used Docker containers before, so don't know much about testing this.

Regarding the persistent data, that would be everything inside the `data` folder and the `config.ini` file. 

You can set the location of this at run time using the flags 
`--datadir=/your/location` 

and 

`--config=/your/location/config.ini`.

**Comment by jkaberg** [comment]
Not bashing @lngarrett work, just: https://github.com/linuxserver/docker-plexpy

**Comment by lngarrett** [comment]
Thanks @jkaberg  I wasn't aware that work had been done. Linuxserver has done a great job. If you guys are interested in using Docker / CircleCI for development and continuous integration I'd still propose adding a Dockerfile to this project. However, I recognize that Travis CI is already being used.

@drzoidberg33: Docker + CI tools can be used to build a Docker image on commit. This allows the latest build to be deployed to a machine running Docker in an automated fashion. It's great for development and also for actual installation.

**Comment by aaronjwood** [comment]
Glad I found this PR, was just about to fork and start this work myself. I was also unaware of https://github.com/linuxserver/docker-plexpy

It'll be really nice to have the option to use this inside of a Linux container.

**Comment by lngarrett** [comment]
since opening this PR, I now use linuxserver's.

**Comment by ssmereka** [comment]
+1 Circle CI and having a dockerfile in the repo.

With the requirement of special version of python (aka not the latest), using a docker container is the easiest way to deploy plexpy.

In addition, adding documentation for using docker with the project would be an extremely helpful couple of lines.

If it would be accepted, I can help get these changes in a pull request.

**Comment by mil1i** [comment]
The docker container no longer works for me at all. I was using linuxserver/plexpy and that was working. But it appears to have updated to the newest build and no longer starts. The tautulli/tautulli docker will not start for me, with the same issue. I am on a CentOS 7 host. 

I've attempted adding the -v /run, does not make a difference.  I've tried creating the docker as privileged.

The below is the error that repeats in the logs when it's attempting to start. Does anyone know what the issue is with the docker containers right now?

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/app/plexpy/PlexPy.py", line 35, in <module>
    import plexpy
  File "/app/plexpy/plexpy/__init__.py", line 59, in <module>
    SCHED = BackgroundScheduler()
  File "/app/plexpy/lib/apscheduler/schedulers/base.py", line 61, in __init__
    self.configure(gconfig, **options)
  File "/app/plexpy/lib/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "/app/plexpy/lib/apscheduler/schedulers/background.py", line 27, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/app/plexpy/lib/apscheduler/schedulers/base.py", line 576, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/app/plexpy/lib/tzlocal/unix.py", line 108, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/plexpy/lib/tzlocal/unix.py", line 41, in _get_localzone
    return _tz_from_env(tzenv)
  File "/app/plexpy/lib/tzlocal/unix.py", line 19, in _tz_from_env
    tz = pytz.timezone(tzenv)
  File "/app/plexpy/lib/pytz/__init__.py", line 167, in timezone
    zone = ascii(zone)
  File "/app/plexpy/lib/pytz/__init__.py", line 71, in ascii
    return s.encode('ASCII')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

**Comment by JonnyWong16** [comment]
This is not the place to post about Docker issues.

https://github.com/Tautulli/Tautulli-Docker

**Pull request closed without merging**
